-- CRIAR PASTA MODULO2 - OK
-- CRIAR NOME DO ARQUIVO (TASK-1.SQL) - OK
-- CRIANDO SCRIPTS...

/*
CREATE TABLE ESTUDANTE (
	id NUMBER NOT NULL,
	nome VARCHAR(200) NOT NULL,
	data_nascimento DATE NOT NULL,
	nr_matricula NUMBER(10) UNIQUE NOT NULL,
	ativo CHAR(1) NOT NULL, -- 'S' = ATIVO , 'N'= NÃO ATIVO
	PRIMARY KEY(id)
);
*/


/*
CREATE SEQUENCE SEQ_ESTUDANTE
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;
*/

-- INSERINDO 10 DADOS NA TABELA ESTUDANTE

/*
INSERT INTO VEM_SER.ESTUDANTE
(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(1, 'MARCKLEN', TO_DATE('03/01/1986','dd-mm-yyyy'), 202301, 'S');
 */

/*
INSERT INTO VEM_SER.ESTUDANTE
(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(2, 'MONTEIRO', TO_DATE('10/02/1988','dd-mm-yyyy'), 202302, 'S');

INSERT INTO VEM_SER.ESTUDANTE
(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(3, 'GUIMARÃES', TO_DATE('25/04/1995','dd-mm-yyyy'), 202303, 'S');

INSERT INTO VEM_SER.ESTUDANTE
(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(4, 'DANIELLE', TO_DATE('07/03/1986','dd-mm-yyyy'), 202304, 'S');

INSERT INTO VEM_SER.ESTUDANTE
(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(5, 'MIGUEL', TO_DATE('15/03/2021','dd-mm-yyyy'), 202305, 'S');

INSERT INTO VEM_SER.ESTUDANTE
(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(6, 'BEATRIZ', TO_DATE('07/10/2010','dd-mm-yyyy'), 202306, 'N');

INSERT INTO VEM_SER.ESTUDANTE
(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(7, 'SORAYA', TO_DATE('31/01/1962','dd-mm-yyyy'), 202307, 'S');

INSERT INTO VEM_SER.ESTUDANTE
(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(8, 'ANTONIO', TO_DATE('19/11/1980','dd-mm-yyyy'), 202308, 'S');

INSERT INTO VEM_SER.ESTUDANTE
(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(9, 'MARIA JULIA', TO_DATE('16/02/2009','dd-mm-yyyy'), 202309, 'N');

INSERT INTO VEM_SER.ESTUDANTE
(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(10, 'MARJORIE', TO_DATE('08/08/2014','dd-mm-yyyy'), 202310, 'N');
*/

SELECT * 
	FROM ESTUDANTE
	WHERE ATIVO = 'S'
	ORDER BY NOME ASC;