-- CRIANDO TABELA PAIS
CREATE TABLE VEM_SER.PAIS(
	id_pais INT PRIMARY KEY NOT NULL,
	nome VARCHAR(200) NOT NULL
);

-- CRIANDO TABELA ESTADO
CREATE TABLE VEM_SER.ESTADO(
    id_estado INT PRIMARY KEY NOT NULL,
    id_pais INT NOT NULL,
    nome VARCHAR2(50) UNIQUE NOT NULL,
    CONSTRAINT FK_PAIS FOREIGN KEY ( id_pais ) REFERENCES PAIS( id_pais )
);

-- CRIANDO TABELA CIDADE
CREATE TABLE VEM_SER.CIDADE(
	id_cidade INT NOT NULL,
	id_estado INT NOT NULL,
	nome VARCHAR2(50) UNIQUE NOT NULL,
	PRIMARY KEY (id_cidade, id_estado),
	CONSTRAINT FK_ESTADO FOREIGN KEY ( id_estado ) REFERENCES ESTADO ( id_estado )
);

-- CRIANDO TABELA BAIRRO
CREATE TABLE VEM_SER.BAIRRO(
	id_bairro INT NOT NULL,
	id_cidade INT NOT NULL,
	id_estado INT NOT NULL,
	nome VARCHAR(50) UNIQUE NOT NULL,
	PRIMARY KEY (id_bairro, id_cidade),
	CONSTRAINT FK_BAIRRO_CIDADE FOREIGN KEY ( id_cidade, id_estado ) REFERENCES CIDADE ( id_cidade, id_estado )
);

-- CRIANDO TABLE ENDERECO
CREATE TABLE VEM_SER.ENDERECO(
	id_endereco INT PRIMARY KEY NOT NULL,
	id_bairro INT NOT NULL,
	id_cidade INT NOT NULL,
	logradourdo VARCHAR(255) NOT NULL,
	numero INT NOT NULL,
	complemento VARCHAR(100),
	cep CHAR(9) NOT NULL,
	CONSTRAINT FK_ENDERECO_BAIRRO FOREIGN KEY ( id_bairro, id_cidade ) REFERENCES BAIRRO ( id_bairro, id_cidade )
);

-- INSERINDO DADOS NAS TABELAS
/*
INSERT INTO VEM_SER.PAIS (ID_PAIS, NOME)
VALUES(SEQ_PAIS.NEXTVAL, 'ARGENTINA');
*/

/*
INSERT INTO VEM_SER.ESTADO (ID_ESTADO, ID_PAIS, NOME)
VALUES(SEQ_ESTADO.NEXTVAL, 2, 'ARIZONA');
*/

/*
INSERT INTO VEM_SER.CIDADE (ID_CIDADE, ID_ESTADO, NOME)
VALUES(SEQ_CIDADE.NEXTVAL, 4, 'TUCSON');
*/

/*
INSERT INTO VEM_SER.BAIRRO (ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME)
VALUES(SEQ_BAIRRO.NEXTVAL, 8, 4, 'JOESLER VILLAGE');
*/

/*
INSERT INTO VEM_SER.ENDERECO
(ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURDO, NUMERO, COMPLEMENTO, CEP)
VALUES(SEQ_ENDERECO.NEXTVAL, 19, 8, 'RUA ONDE ANDA VOCE', 0235, 'TOQUINHO/VINICIUS', '96550-669');
*/


--SELECT * FROM VEM_SER.ENDERECO e;
--SELECT * FROM VEM_SER.ESTADO es;
--SELECT * FROM VEM_SER.CIDADE c ORDER BY ID_CIDADE;
SELECT * FROM VEM_SER.BAIRRO b ORDER BY ID_BAIRRO;
--SELECT * FROM VEM_SER.PAIS p;

--DELETE FROM VEM_SER.PAIS p WHERE p.ID_PAIS = 3;

-- CRIANDO SEQUENCES
/* 
CREATE SEQUENCE VEM_SER.SEQ_ENDERECO
	START WITH 1
	INCREMENT BY 1
	NOCACHE NOCYCLE;
*/

-- DROP TABLE VEM_SER.PAIS  
-- DROP SEQUENCE VEM_SER.SEQ_PAIS


/** OUTRAS MANEIRAS DE CRIAÇÃO E ALTERAÇÃO DE TABELA PÓS CRIAÇÃO

CREATE TABLE VEM_SER.ESTADO(
    id_estado NUMBER PRIMARY KEY NOT NULL,
    nome VARCHAR2(50) UNIQUE NOT NULL
);

ALTER TABLE VEM_SER.ESTADO
ADD id_pais INT NOT NULL;

ALTER TABLE VEM_SER.ESTADO
ADD CONSTRAINT FK_ID_PAIS FOREIGN KEY ( id_pais ) REFERENCES PAIS( id_pais );

***/