-------------------------------------------------------------------------------
-- FAZER UM RIGHT JOIN ENTRE TABELA PESSOA x CONTATO --
SELECT
	p.NOME "nomePessoa",
	c.NUMERO "numeroContato"
FROM
	VEM_SER.PESSOA p
RIGHT JOIN
	CONTATO c
ON
	p.ID_PESSOA = c.ID_PESSOA;
-- FAZER UM RIGHT JOIN TABELA PESSOA x PESSOA_X_PESSOA_ENDERECO x ENDERECO_PESSOA --
SELECT
	p.NOME,
	ep.ESTADO
FROM
	VEM_SER.PESSOA p
RIGHT JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO pxpe ON (p.ID_PESSOA = pxpe.ID_PESSOA)
RIGHT JOIN VEM_SER.ENDERECO_PESSOA ep ON (ep.ID_ENDERECO = pxpe.ID_ENDERECO)
-- FAZER UM RIGHT JOIN ENTRE TODAS AS TABELAS (COMEÇANDO POR PESSOA) --
SELECT
	p.NOME "nomePessoa",
	ep.ESTADO "estado",
	c.NUMERO "numeroContato"
FROM
	VEM_SER.PESSOA p
RIGHT JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO pxpe ON (pxpe.ID_PESSOA = p.ID_PESSOA)
RIGHT JOIN VEM_SER.ENDERECO_PESSOA ep ON (ep.ID_ENDERECO = pxpe.ID_ENDERECO)
RIGHT JOIN VEM_SER.CONTATO c ON (p.ID_PESSOA = c.ID_PESSOA)
-------------------------------------------------------------------------------
-- FAZER UM OUTER FULL JOIN ENTRE TABELAS - PESSOA e CONTATO
SELECT
	p.NOME "nomePessoa",
	p.DATA_NASCIMENTO "dataDeNascimento",
	c.NUMERO "numeroContato"
FROM
	VEM_SER.PESSOA p
FULL JOIN
	CONTATO c
ON
	(p.ID_PESSOA = c.ID_PESSOA)
ORDER BY p.DATA_NASCIMENTO;

-- FAZER UM OUTER FULL JOIN ENTRE TABELAS - PESSOA e PESSOA_X_PESSOA_ENDERECO e ENDERECO_PESSOA
SELECT
	p.NOME,
	ep.ESTADO
FROM
	VEM_SER.PESSOA p
FULL JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO pxpe ON (p.ID_PESSOA = pxpe.ID_PESSOA)
FULL JOIN VEM_SER.ENDERECO_PESSOA ep ON (ep.ID_ENDERECO = pxpe.ID_ENDERECO)

-- FAZER UM OUTER FULL JOIN ENTRE TODAS AS TABELAS (COMEÇANDO POR PESSOA)

SELECT
	p.NOME "nomePessoa",
	ep.ESTADO "estado",
	c.NUMERO "numeroContato"
FROM
	VEM_SER.PESSOA p
FULL JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO pxpe ON (pxpe.ID_PESSOA = p.ID_PESSOA)
FULL JOIN VEM_SER.ENDERECO_PESSOA ep ON (ep.ID_ENDERECO = pxpe.ID_ENDERECO)
FULL JOIN VEM_SER.CONTATO c ON (p.ID_PESSOA = c.ID_PESSOA)
-------------------------------------------------------------------------------
-- UTILIZANDO EXISTS SELECIONE AS PESSOAS QUE TEM ENDEREÇO
SELECT 
	* 
FROM 
	VEM_SER.PESSOA p 
WHERE EXISTS 
	(SELECT pxpe.ID_ENDERECO
	   FROM VEM_SER.PESSOA_X_PESSOA_ENDERECO pxpe 
	  WHERE pxpe.ID_PESSOA = p.ID_PESSOA);
-- SELECIONE ID E NOME DA TABELA PESSOA JUNTO COM ID E LOGRADOURO DA TABELA ENDERECO_PESSOA
SELECT
	p.ID_PESSOA "idPessoa",
	p.NOME "nomePessoa",
	ep.ID_ENDERECO "idEndereco",
	ep.LOGRADOURO "endereco"
FROM
	VEM_SER.PESSOA p
INNER JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO pxpe ON p.ID_PESSOA = pxpe.ID_PESSOA
INNER JOIN VEM_SER.ENDERECO_PESSOA ep ON ep.ID_ENDERECO = pxpe.ID_ENDERECO
-- UTILIZANDO UNION
SELECT
	p.ID_PESSOA "ID_PESSOA",
	p.NOME "NOME_PESSOA"
FROM 
	VEM_SER.PESSOA p
UNION
	SELECT 
		ep.ID_ENDERECO,
		ep.LOGRADOURO
	FROM 
		VEM_SER.ENDERECO_PESSOA ep;